language: java
jdk:
  - openjdk11

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-study-project-qrna *
  - mkdir -p deploy
  - mv springboot-study-project-qrna.zip deploy/springboot-study-project-qrna.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: qrna-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
notifications:
  email:
    recipients:
      - piq2255@gamil.com